<!-- Projeto Desenvolvido na Data Science Academy - www.datascienceacademy.com.br -->
# <font color='blue'>Data Science Academy</font>
## <font color='blue'>Matemática e Estatística Aplicada Para Data Science, Machine Learning e IA</font>
## <font color='blue'>Lista de Exercícios 4</font>
## <font color='blue'>Operações com Vetores em Análise de Dados e Data Science</font>

### Instalando e Carregando Pacotes

In [1]:
# Para atualizar um pacote, execute o comando abaixo no terminal ou prompt de comando:
# pip install -U nome_pacote

# Para instalar a versão exata de um pacote, execute o comando abaixo no terminal ou prompt de comando:
# !pip install nome_pacote==versão_desejada

# Depois de instalar ou atualizar o pacote, reinicie o jupyter notebook.

# Instala o pacote watermark. 
# Esse pacote é usado para gravar as versões de outros pacotes usados neste jupyter notebook.
!pip install -q -U watermark

In [2]:
# Imports
import numpy as np
import scipy

In [3]:
# Versões dos pacotes usados neste jupyter notebook
%reload_ext watermark
%watermark -a "Data Science Academy" 

Author: Data Science Academy



**Resolva os exercícios abaixo usando Linguagem Python. Faça pesquisa complementar se necessário.**

### Exercício 1: Produto Escalar em Aplicação Prática

Descrição: Dados dois vetores que representam preferências de usuários em três categorias diferentes user1 = [4, 3, 2] e user2 = [1, 5, 4], calcule a similaridade entre esses usuários usando o produto escalar. 

In [4]:
# Vetores
user1 = np.array([4, 3, 2])
user2 = np.array([1, 5, 4])

# Produto escalar
similaridade = np.dot(user1, user2)
print(similaridade)

27


O produto escalar entre dois vetores, também conhecido como produto interno ou dot product, é uma operação matemática que resulta em um único número. Este número é uma medida de certos tipos de similaridade entre os dois vetores. Agora, interpretando o valor de 27:

**Magnitude da Similaridade**: O valor absoluto (27 neste caso) indica a magnitude da similaridade. Quanto maior esse número, maior é a similaridade sob a métrica específica que o produto escalar representa.

**Direção e Orientação**: O produto escalar é positivo quando os vetores apontam na mesma direção geral e negativo quando apontam em direções opostas. Um valor de 27, sendo positivo, sugere que user1 e user2 têm uma orientação geral semelhante no espaço vetorial considerado.

**Contexto Específico**: A interpretação mais precisa depende do contexto onde esses vetores são aplicados. Por exemplo, se estes vetores representam preferências ou características em um sistema de recomendação, um valor alto pode indicar uma alta similaridade nessas preferências ou características.

**Normalização**: É importante considerar a magnitude dos vetores originais. Se os vetores forem muito grandes, até mesmo vetores relativamente diferentes podem ter um produto escalar alto. Em muitos casos, é útil normalizar os vetores antes de calcular o produto escalar para obter uma medida de similaridade mais significativa.

### Exercício 2: Multiplicação de Escalar por Vetor em Dados Reais

Descrição: Dada uma série de preços de ações prices = [120, 125, 130, 128, 135], ajuste os preços em 15% e calcule o novo preço das ações.

In [5]:
# Preços
prices = np.array([120, 125, 130, 128, 135])

# Fator de ajuste
fator = 1.15

# Cálculo
precos_ajustados = prices * fator

# Resultado
print(precos_ajustados)

[138.   143.75 149.5  147.2  155.25]


### Exercício 3: Otimização de Produto Escalar

Descrição: Encontre o vetor unitário que maximiza o produto escalar com o vetor v = [3, 4, 5]. Use técnicas de otimização para encontrar a solução.

In [6]:
from scipy.optimize import minimize

# Array
v = np.array([3, 4, 5])

# Função objetivo
def funcao_objetivo(x):
    return -np.dot(v, x)

# Restrição para garantir que o vetor seja unitário
constraint = {'type': 'eq', 'fun': lambda x: np.linalg.norm(x) - 1}

# Solução de otimização
resultado = minimize(funcao_objetivo, np.ones(3), constraints = constraint)
vetor_otimizado = resultado.x

print(vetor_otimizado)

[0.42427197 0.56568183 0.70710492]


O objetivo é encontrar um vetor que maximize o produto escalar com um vetor dado v, sob a restrição de que o vetor resultante seja unitário (isto é, tenha norma igual a 1). 

No SciPy, **minimize** é uma função geral para otimização numérica de funções escalares.

A função "funcao_objetivo" é a função objetivo a ser otimizada. Ela calcula o produto escalar negativo do vetor v com um vetor x. O sinal negativo é usado porque a função minimize procura minimizar o valor da função objetivo. Neste caso, minimizar o negativo do produto escalar é o mesmo que maximizar o produto escalar.

A variável **constraint** é a restrição que exige que a norma (ou magnitude) do vetor x seja 1, tornando-o um vetor unitário. A chave 'type': 'eq' indica que é uma restrição de igualdade, ou seja, a função deve resultar em zero.

Esta linha abaixo:

resultado = minimize(funcao_objetivo, np.ones(3), constraints = constraint)

chama a função minimize, passando a função objetivo, um vetor inicial de [1, 1, 1] (três uns) e a restrição definida. A função minimize irá ajustar o vetor inicial para encontrar o vetor que maximiza o produto escalar com v enquanto mantém sua norma igual a 1.

Após a otimização, o vetor resultante é armazenado na propriedade x do objeto resultado. Este vetor é o vetor unitário que maximiza o produto escalar com v sob a restrição dada.

O código acima usa otimização numérica para encontrar um vetor unitário que tenha o máximo produto escalar possível com o vetor [3, 4, 5].

Acabamos de reproduzir (de forma simplificada) a ideia por trás do algoritmo de descida do gradiente, a principal técnica usada no treinamento de modelos de Deep Learning e diversos algoritmos mais simples de Machine Learning.

Machine Learning é, de fato, um problema de otimização matemática, onde queremos minimizar a função objetivo (função de erro), encontrando valores que façam com que a função tenha o menor resultado possível, ou seja, o modelo de Machine Learning tenha o menor erro possível.

In [ ]:
# Calculando o produto escalar entre o vetor inicial e o vetor resultante
produto_escalar = np.dot(v, vetor_otimizado)
produto_escalar

O produto escalar entre o vetor inicial e o vetor resultante da otimização é aproximadamente 
7.1. Este resultado indica a máxima similaridade alcançada entre o vetor inicial e um vetor unitário sob as condições definidas na otimização. 

### Exercício 4: Produto Vetorial e Direção Normal

Descrição: Dados três pontos no espaço 3D A = [1, 2, 3], B = [4, 5, 6], e C = [7, 8, 9], encontre um vetor normal ao plano definido por esses três pontos.

In [7]:
# Definição dos pontos
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
C = np.array([7, 8, 9])

# Cálculo dos vetores direcionais a partir dos pontos
AB = B - A
AC = C - A

# Cálculo do produto vetorial para encontrar o vetor normal
vetor_normal = np.cross(AB, AC)
print(vetor_normal)

[0 0 0]


### Exercício 5: Produto Vetorial em Análise de Dados

Descrição: Em um conjunto de dados 3D com pontos p1 = [1, 2, 3], p2 = [4, 5, 6], e p3 = [7, 8, 9], encontre o vetor normal ao plano formado por esses três pontos e interprete seu significado em termos de orientação do plano.

Resposta:

O vetor normal ao plano definido pelos pontos A = [1, 2, 3], B = [4, 5, 6], e C = [7, 8, 9] resultou em [0, 0, 0]. Isso ocorre porque os pontos A, B, e C são colineares no espaço 3D, ou seja, eles estão alinhados em uma única linha reta. Portanto, não formam um plano distinto no qual um vetor normal único possa ser definido.

Em termos geométricos, quando três pontos são colineares, os vetores que os conectam (neste caso, AB e AC) são paralelos ou antiparalelos. O produto vetorial de dois vetores paralelos ou antiparalelos é sempre zero, o que explica o resultado obtido. 

In [8]:
%reload_ext watermark
%watermark -a "Data Science Academy"

Author: Data Science Academy



In [9]:
#%watermark -v -m

In [10]:
#%watermark --iversions

# Fim