<!-- Projeto Desenvolvido na Data Science Academy - www.datascienceacademy.com.br -->
# <font color='blue'>Data Science Academy</font>
## <font color='blue'>Matemática e Estatística Aplicada Para Data Science, Machine Learning e IA</font>
## <font color='blue'>Lab 3</font>
## <font color='blue'>Regras Básicas da Álgebra, Operações com Vetores e Algoritmo de Machine Learning</font>

### Instalando e Carregando Pacotes

In [1]:
# Para atualizar um pacote, execute o comando abaixo no terminal ou prompt de comando:
# pip install -U nome_pacote

# Para instalar a versão exata de um pacote, execute o comando abaixo no terminal ou prompt de comando:
# !pip install nome_pacote==versão_desejada

# Depois de instalar ou atualizar o pacote, reinicie o jupyter notebook.

# Instala o pacote watermark. 
# Esse pacote é usado para gravar as versões de outros pacotes usados neste jupyter notebook.
!pip install -q -U watermark

In [2]:
# Imports
import math
import numpy as np

In [3]:
# Versões dos pacotes usados neste jupyter notebook
%reload_ext watermark
%watermark -a "Data Science Academy" 

Author: Data Science Academy



## Regras Básicas da Álgebra

> Propriedades da Igualdade

In [4]:
# Reflexiva
# Qualquer número ou expressão é igual a si mesmo
a = 5
print(a == a)  # True

True


In [5]:
# Simétrica
a = 5
b = 5
print(a == b)  # True
print(b == a)  # True

True
True


In [6]:
# Transitiva
a = 5
b = 5
c = 5
print(a == b and b == c)  # True
print(a == c)  # True

True
True


> Propriedades das Operações

In [7]:
# Comutativa (Adição e Multiplicação) 
# A ordem dos números não afeta a soma ou o produto
a = 3
b = 4
print(a + b == b + a)  # True
print(a * b == b * a)  # True

True
True


In [8]:
# Associativa (Adição e Multiplicação)
# A maneira como os números são agrupados não afeta a soma ou o produto
a = 3
b = 4
c = 5
print((a + b) + c == a + (b + c))  # True
print((a * b) * c == a * (b * c))  # True

True
True


In [9]:
# Distributiva
a = 3
b = 4
c = 5
print(a * (b + c) == a * b + a * c)  # True

True


> Elementos Neutros e Inversos

In [10]:
# Elemento Neutro da Adição (0)
a = 7
print(a + 0 == a)  # True

True


In [11]:
# Elemento Neutro da Multiplicação (1)
a = 7
print(a * 1 == a)  # True

True


In [12]:
# Inverso Aditivo
a = 7
print(a + (-a) == 0)  # True

True


In [13]:
# Inverso Multiplicativo
a = 7
print(a * (1/a) == 1)  # True

True


> Regras de Exponenciação

In [14]:
# Produto de Mesma Base
print(2**3 * 2**4 == 2**(3+4))  # True

True


In [15]:
# Divisão de Mesma Base
print(2**5 / 2**2 == 2**(5-2))  # True

True


In [16]:
# Potência de uma Potência
print((2**3)**2 == 2**(3*2))  # True

True


In [17]:
# Potência de um Produto
print((2*3)**2 == 2**2 * 3**2)  # True 

True


In [18]:
# Exponencial Zero
print(2**0 == 1)  # True

True


> Regras de Radicais

In [19]:
# Raiz de um Produto ** ATENÇÃO AO CÁLCULO DE PONTO FLUTUANTE **
print(math.sqrt(2*8) == math.sqrt(2) * math.sqrt(8))  # True

False


In [20]:
# Vamos adicionar tolerância ao cálculo (afinal, o mundo precisa mesmo de mais tolerância! :-)
a = math.sqrt(2*8)
b = math.sqrt(2) * math.sqrt(8)
tolerance = 1e-10

print(abs(a - b) < tolerance)  # Deve retornar True

True


In [21]:
# Raiz de um Quociente
print(math.sqrt(16/4) == math.sqrt(16) / math.sqrt(4))  # True

True


> Regras de Polinômios (Adição e Subtração de Termos Semelhantes)

In [22]:
# Regras de Polinômios (Adição e Subtração de Termos Semelhantes):

# Polinômios: 2x^2 + 3x + 4 e 3x^2 - 2x + 1
# Adição: (2x^2 + 3x^2) + (3x - 2x) + (4 + 1)

# Variável
x = 2

# Calcula a adição dos polinômios
print((2*x**2 + 3*x**2) + (3*x - 2*x) + (4 + 1))  

27


> Regras de Frações

In [23]:
# Multiplicação
# Frações: (1/2) * (3/4)
print((1/2) * (3/4))  # 0.375

0.375


In [24]:
# Divisão
# Frações: (1/2) / (3/4) = (1/2) * (4/3)
print((1/2) / (3/4))  # 0.666...

0.6666666666666666


In [25]:
# Soma e Subtração com Denominador Comum:
# Frações: (1/4) + (3/4)
print((1/4) + (3/4))  # 1.0

1.0


## Operações com Vetores - Adição e Subtração

In [26]:
# Definindo dois vetores como listas
vetor_a = [3, 4, 5]
vetor_b = [1, 2, 3]

In [27]:
# Função para adição de vetores
def adicionar_vetores(a, b):
    return [a[i] + b[i] for i in range(len(a))]

In [28]:
# Função para subtração de vetores
def subtrair_vetores(a, b):
    return [a[i] - b[i] for i in range(len(a))]

In [29]:
# Realizando as operações
vetor_soma = adicionar_vetores(vetor_a, vetor_b)
vetor_diferenca = subtrair_vetores(vetor_a, vetor_b)

In [30]:
# Mostrando os resultados
print("Vetor A:", vetor_a)
print("Vetor B:", vetor_b)
print("Soma dos Vetores:", vetor_soma)
print("Diferença dos Vetores:", vetor_diferenca)

Vetor A: [3, 4, 5]
Vetor B: [1, 2, 3]
Soma dos Vetores: [4, 6, 8]
Diferença dos Vetores: [2, 2, 2]


## Operações com Vetores - Cross Product (Produto Vetorial)

O produto vetorial entre dois vetores resulta em um terceiro vetor que é perpendicular aos dois vetores originais. 

In [31]:
# Função para calcular o produto vetorial entre 2 vetores
def produto_vetorial(v1, v2):
    x = v1[1] * v2[2] - v1[2] * v2[1]
    y = v1[2] * v2[0] - v1[0] * v2[2]
    z = v1[0] * v2[1] - v1[1] * v2[0]
    return [x, y, z]

In [32]:
# Cria os vetores
vetor_a = [2, -3, 1]
vetor_b = [5, 7, 6]

In [33]:
# Calculando o produto vetorial
resultado = produto_vetorial(vetor_a, vetor_b)
print("Produto Vetorial:", resultado)

Produto Vetorial: [-25, -7, 29]


https://www.wolframalpha.com/input/?i=cross+product+calculator

https://www.mathsisfun.com/algebra/vectors-cross-product.html

## Operações com Vetores - Dot Product (Produto Escalar)

O produto escalar de dois vetores é uma operação que resulta em um escalar (um número). Matematicamente, é a soma dos produtos dos componentes correspondentes dos vetores.

In [34]:
# Função para calcular o produto escalar
def produto_escalar(v1, v2):
    return sum(a * b for a, b in zip(v1, v2))

In [35]:
# Cria os vetores
vetor_a = [2, -3, 1]
vetor_b = [5, 7, 6]

In [36]:
# Calculando o produto escalar
resultado = produto_escalar(vetor_a, vetor_b)
print("Produto Escalar:", resultado)

Produto Escalar: -5


https://www.wolframalpha.com/input?i=dot+product

https://www.mathsisfun.com/algebra/vectors-dot-product.html

<!-- Projeto Desenvolvido na Data Science Academy - www.datascienceacademy.com.br -->

## Machine Learning Apenas com Operações Matemáticas (Sem Uso de Frameworks)

Vamos criar um modelo capaz de prever o preço de um ativo financeiro com base na taxa nominal de juros.

In [37]:
# Gerando dados sintéticos
np.random.seed(0)
X = np.random.randint(1, 10, size = (100, 1))  # 100 instâncias, valores entre 1 e 10
y = 50000 + 30000 * X + np.random.randn(100, 1) * 15000  # Relação linear: preço base + preço por ativo + ruído

In [38]:
# Visualizando alguns registros
X[1:5]

array([[1],
       [4],
       [4],
       [8]])

In [39]:
# Visualizando alguns registros
y[1:5]

array([[ 85385.04146705],
       [186141.81556278],
       [172882.11251578],
       [302793.88936252]])

In [40]:
# Adicionar coluna de uns para o termo de interceptação
X_b = np.c_[np.ones((100, 1)), X]  # Adiciona x0 = 1 a cada instância

### Função de Custo MSE com Operações Entre Vetores

Esta função dsa_func_custo é uma implementação da função de custo de erro quadrático médio, que é amplamente usada em regressão linear. O objetivo dessa função é medir quão bem o modelo de regressão (representado pelos parâmetros theta) está desempenhando em relação ao conjunto de dados (X e y). Um custo mais baixo indica que o modelo está fazendo previsões mais precisas.

In [41]:
# Função de Custo MSE com Operações Entre Vetores
def dsa_func_custo(X, y, theta):
    
    # m é o número de exemplos de treinamento (observações) no conjunto de dados
    m = len(y)

    # Calcula a função de custo para a regressão linear
    # A função de custo é a média dos erros quadrados entre as previsões e os valores reais
    # (1/(2*m)) é um fator de escala comum na função de custo do erro quadrático médio
    # np.sum(np.square(X.dot(theta) - y)) é a soma dos quadrados dos erros
    # X.dot(theta) é o produto escalar de X (dados de entrada) e theta (parâmetros do modelo)
    # X.dot(theta) - y é a diferença entre as previsões e os valores reais
    cost = (1/(2*m)) * np.sum(np.square(X.dot(theta) - y))

    # Retorna o custo calculado
    return cost

### Algoritmo Gradiente Descendente com Operações Entre Vetores

In [42]:
# Gradiente descendente
def dsa_gradient_descent(X, y, theta, learning_rate, iterations):
    
    # m é o número de exemplos de treinamento no conjunto de dados
    m = len(y)

    # Inicializa um array para armazenar o histórico de custo em cada iteração
    cost_history = np.zeros(iterations)

    # Loop para realizar o número especificado de iterações
    for i in range(iterations):
        
        # Calcula o gradiente da função de custo em relação a theta
        # O gradiente é a média dos produtos dos erros e as características de entrada
        gradients = 1/m * X.T.dot(X.dot(theta) - y)

        # Atualiza os parâmetros theta subtraindo o produto da taxa de aprendizado e o gradiente
        # Esta é a etapa de descida do gradiente, movendo-se em direção ao mínimo da função de custo
        theta = theta - learning_rate * gradients

        # Calcula o custo com o theta atualizado e armazena no histórico de custo
        cost_history[i] = dsa_func_custo(X, y, theta)
    
    # Retorna os parâmetros theta otimizados e o histórico de custo
    return theta, cost_history

### Treinamento do Modelo

In [43]:
# Parâmetros iniciais

# Inicializa os parâmetros randomicamente
theta = np.random.randn(2, 1)

# Taxa de aprendizado
learning_rate = 0.01

# Número de passadas de treino
iterations = 1000

In [44]:
# Treinando o modelo
theta_final, cost_history = dsa_gradient_descent(X_b, y, theta, learning_rate, iterations)

In [45]:
print("Modelo de Machine Learning - Parâmetros Finais:\n", theta_final)

Modelo de Machine Learning - Parâmetros Finais:
 [[44287.25556464]
 [31108.64267429]]


### Deploy e Previsão com Novos Dados

In [46]:
# Novo valor de X
X_new = np.array([[4.5]])

In [47]:
# Novo valor do bias
X_new_b = np.c_[np.ones((1, 1)), X_new]

In [48]:
# Previsão
y_predict = X_new_b.dot(theta_final)

In [49]:
print("Com base na taxa de juros nominal, esta é a previsão do preço do ativo:", np.round(y_predict, 2))

Com base na taxa de juros nominal, esta é a previsão do preço do ativo: [[184276.15]]


In [50]:
%reload_ext watermark
%watermark -a "Data Science Academy"

Author: Data Science Academy



In [51]:
#%watermark -v -m

In [52]:
#%watermark --iversions

# Fim