<!-- Projeto Desenvolvido na Data Science Academy - www.datascienceacademy.com.br -->
# <font color='blue'>Data Science Academy</font>
## <font color='blue'>Matemática e Estatística Aplicada Para Data Science, Machine Learning e IA</font>
## <font color='blue'>Lab 5</font>
### <font color='blue'>Operações com Matrizes, Determinantes, Autovalores e Autovetores em Ciência de Dados</font>

## Instalando e Carregando os Pacotes

In [1]:
# Para atualizar um pacote, execute o comando abaixo no terminal ou prompt de comando:
# pip install -U nome_pacote

# Para instalar a versão exata de um pacote, execute o comando abaixo no terminal ou prompt de comando:
# !pip install nome_pacote==versão_desejada

# Depois de instalar ou atualizar o pacote, reinicie o jupyter notebook.

# Instala o pacote watermark. 
# Esse pacote é usado para gravar as versões de outros pacotes usados neste jupyter notebook.
#!pip install -q -U watermark

In [2]:
# Imports
import numpy as np

In [3]:
# Versões dos pacotes usados neste jupyter notebook
%reload_ext watermark
%watermark -a "Data Science Academy" 

Author: Data Science Academy



## Multiplicação de Matrizes

In [4]:
x = np.array([[1,3],[5,7]])
print(x)

[[1 3]
 [5 7]]


In [5]:
y = np.array([[2,4],[6,8]])
print(y)

[[2 4]
 [6 8]]


In [6]:
x * y

array([[ 2, 12],
       [30, 56]])

In [7]:
np.matmul(x, y)

array([[20, 28],
       [52, 76]])

In [8]:
x @ y

array([[20, 28],
       [52, 76]])

In [9]:
np.cross(x, y)

array([-2, -2])

In [10]:
np.dot(x, y)

array([[20, 28],
       [52, 76]])

In [11]:
np.dot(x, x.T)

array([[10, 26],
       [26, 74]])

In [12]:
np.sqrt(np.sum(x ** 2))

9.16515138991168

Vamos analisar cada uma das operações utilizando as matrizes x e y:

**x * y**: Esta é uma multiplicação elemento a elemento (element-wise). Cada elemento da matriz x é multiplicado pelo elemento correspondente na mesma posição na matriz y. Não é uma multiplicação de matrizes, mas sim uma operação aplicada individualmente a cada par de elementos correspondentes.

**np.matmul(x, y)**: Esta é a multiplicação de matrizes propriamente dita, também conhecida como produto matricial. Aqui, o resultado é uma nova matriz onde cada elemento é calculado como a soma dos produtos dos elementos correspondentes nas linhas de x e nas colunas de y. Referência:

https://mathworld.wolfram.com/MatrixMultiplication.html

**x @ y**: Este é o operador de multiplicação de matrizes. Funciona da mesma forma que np.matmul(x, y), realizando a multiplicação de matrizes.

**np.cross(x, y)**: Esta operação calcula o produto vetorial (ou produto cruzado) de x e y. Como x e y são matrizes 2x2, a função np.cross tratará as linhas de cada matriz como vetores e calculará o produto vetorial linha a linha.

**np.dot(x, y)**: Para matrizes bidimensionais, np.dot(x, y) é equivalente a np.matmul(x, y). Calcula o produto matricial de x e y.

**np.dot(x, x.T)**: Aqui, x.T é a transposta de x. Esta operação realiza o produto matricial de x com sua transposta. O resultado é uma matriz que representa, de certa forma, o "produto escalar" da matriz com ela mesma, mas em termos de suas linhas ou colunas, dependendo da orientação da multiplicação.

**np.sqrt(np.sum(x ** 2))**: Esta expressão calcula a norma Frobenius da matriz x. Primeiro, eleva cada elemento de x ao quadrado e soma todos esses quadrados. Em seguida, calcula a raiz quadrada do resultado. Isso dá uma medida geral da magnitude da matriz x.

Cada uma dessas operações tem seu uso específico e é fundamental entender essas diferenças para aplicá-las corretamente em contextos matemáticos e de programação.

### Multiplicação Element-wise

Já vimos a multiplicação de matrizes com element-wise. Apenas para relembrar:

In [13]:
# Definimos uma matriz
m = np.array([[1,2,3], [4,5,6]])
print(m)

[[1 2 3]
 [4 5 6]]


In [14]:
m.shape

(2, 3)

In [15]:
# Usamos o operador de multiplicação para multiplicar cada elemento da matriz por 3. 
# Isso vai gerar uma nova matriz n.
n = m * 3
print(n)

[[ 3  6  9]
 [12 15 18]]


In [16]:
n.shape

(2, 3)

In [17]:
# Multiplicamos as duas matrizes, element-wise
matriz_resultado = m * n

In [18]:
print(matriz_resultado)

[[  3  12  27]
 [ 48  75 108]]


In [19]:
matriz_resultado.shape

(2, 3)

### Multiplicação de Matrizes x Multiplicação Element-wise

> Imagine agora que precisamos multiplicar as duas matrizes abaixo:

In [20]:
a = np.array([[1,2,3,4],[5,6,7,8]])

In [21]:
a.shape

(2, 4)

In [22]:
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [23]:
b.shape

(4, 3)

In [24]:
# Operação element-wise
a * b

ValueError: operands could not be broadcast together with shapes (2,4) (4,3) 

Por que a mensagem de erro?

A operação a * b usando arrays NumPy não funciona no contexto acima porque representa uma multiplicação elemento a elemento e não uma multiplicação de matrizes. Para que a multiplicação elemento a elemento funcione, as matrizes envolvidas devem ter o mesmo tamanho (número de linhas e colunas) ou devem ser compatíveis de acordo com as regras de broadcasting do NumPy.

A operação a * b tenta multiplicar elemento a elemento duas matrizes que não são compatíveis em termos de forma (shape). Em outras palavras, não há um mapeamento um-para-um entre cada elemento de a e b que permita essa multiplicação.

Se você quiser realizar a multiplicação de matrizes, você deve usar np.dot(a, b) ou np.matmul(a, b). Estas funções são projetadas para lidar com a multiplicação de matrizes onde as dimensões internas das matrizes (colunas de a, linhas de b) são compatíveis.

In [25]:
np.matmul(a, b)

array([[ 70,  80,  90],
       [158, 184, 210]])

In [26]:
# Essa notação é a mesma coisa que matmul()
a @ b

array([[ 70,  80,  90],
       [158, 184, 210]])

### Matrix Product

https://numpy.org/doc/stable/reference/generated/numpy.matmul.html

A definição de multiplicação de matrizes indica uma multiplicação linha por coluna, onde as entradas na i-ésima linha de A são multiplicados pelas entradas correspondentes no jth coluna de B e, em seguida, somando os resultados.

A multiplicação de matrizes NÃO é comutativa.

Para encontrar o produto da matriz, você usa a função matmul() do NumPy. **O shape das matrizes precisa ser compatível.**

**Aqui estão as regras para o produto das matrizes:**

•	O número de colunas na matriz esquerda deve ser igual ao número de linhas na matriz direita (logo, a ordem das matrizes na multiplicação é importante).

•	A matriz resultante da operação possui o mesmo número de linhas que a matriz esquerda e o mesmo número de colunas que a matriz direita.

•	Ordem importa aqui. Multiplicar A • B não é o mesmo que multiplicar B • A.

•	Os dados na matriz esquerda devem ser organizados como linhas, enquanto os dados na matriz direita devem ser organizados como colunas.


In [27]:
# Não podemos usar matmul nas matrizes do exemplo anterior pois viola uma das regras
np.matmul(m, n)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [28]:
a = np.array([[1,2,3,4], [5,6,7,8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [29]:
a.shape

(2, 4)

In [30]:
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(b)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [31]:
b.shape

(4, 3)

In [32]:
# Matrix Product
matriz_reposta = np.matmul(a, b)

In [33]:
print(matriz_reposta)

[[ 70  80  90]
 [158 184 210]]


In [34]:
matriz_reposta.shape

(2, 3)

In [35]:
# Se as matrizes tiverem shape incompatível, você recebe a mensagem de erro abaixo.
# Veja que A x B não é a mesma coisa que B x A na multiplicação de matrizes.
np.matmul(b, a)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

### Produto Escalar de Matrizes

https://numpy.org/doc/stable/reference/generated/numpy.dot.html

O produto escalar (dot product) é a soma dos produtos dos elementos correspondentes nas duas matrizes. Para obter o produto escalar, o número de colunas da primeira matriz deve ser igual ao número de linhas da segunda matriz.

O mesmo problema do exemplo anterior aconteceria aqui devido à diferença nos shapes.

In [36]:
np.dot(b, a)

ValueError: shapes (4,3) and (2,4) not aligned: 3 (dim 1) != 2 (dim 0)

Agora sim:

In [37]:
np.dot(a, b)

array([[ 70,  80,  90],
       [158, 184, 210]])

> Dot product com escalares:

In [38]:
# Dois escalares
k = 5
j = 7

print(np.dot(k, j))

35


> Dot product com vetores:

In [39]:
# Vetores
c = [3, 4, 5]
d = [6, 7, 8]
 
print(np.dot(c, d))

86


> Dot product com matrizes:

In [40]:
# Matrizes
m1 = [[2, 1], [0, 3]]
m2 = [[1, 1], [3, 2]]
 
print(np.dot(m1, m2))

[[5 4]
 [9 6]]


> Dot product com matrizes (se inverter a ordem o resultado é diferente):

In [41]:
print(np.dot(m2, m1))

[[2 4]
 [6 9]]


In [42]:
z = np.array([[1,2],[3,4]])
print(z)

[[1 2]
 [3 4]]


In [43]:
np.dot(z, z)

array([[ 7, 10],
       [15, 22]])

In [44]:
# Podemos chamar a função dot() diretamente do objeto ndarray
z.dot(z) 

array([[ 7, 10],
       [15, 22]])

In [45]:
# Matmul gera o mesmo resultado porque as dimensões são as mesmas (mesma matriz)
np.matmul(z, z)

array([[ 7, 10],
       [15, 22]])

Por que o resultado é o mesmo nas duas operações abaixo?

In [46]:
a = np.array([[1,2,3,4], [5,6,7,8]])

In [47]:
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [48]:
np.matmul(a, b)

array([[ 70,  80,  90],
       [158, 184, 210]])

In [49]:
np.dot(a, b)

array([[ 70,  80,  90],
       [158, 184, 210]])

As duas expressões np.matmul(a, b) e np.dot(a, b) geram o mesmo resultado neste caso específico porque ambas realizam a multiplicação de matrizes entre a e b. No entanto, é importante entender que np.matmul e np.dot são diferentes em termos mais gerais e podem produzir resultados diferentes em outros contextos (como veremos a seguir).

**np.matmul**: Esta função é usada especificamente para a multiplicação de matrizes. No caso de arrays bidimensionais (matrizes), np.matmul(a, b) é equivalente à multiplicação de matrizes padrão.

**np.dot**: A função np.dot é usado para realizar tanto o produto escalar (dot product) quanto a multiplicação de matrizes. Para arrays bidimensionais, np.dot(a, b) comporta-se como uma multiplicação de matrizes. No entanto, para arrays com mais de duas dimensões, np.dot e np.matmul podem se comportar de maneira diferente.

Em nosso caso, ambas as matrizes a e b são bidimensionais. A matriz a tem dimensões 2x4 e a matriz b tem dimensões 4x3. A regra de multiplicação de matrizes diz que, para multiplicar duas matrizes, o número de colunas da primeira matriz (a) deve ser igual ao número de linhas da segunda matriz (b). Aqui, a (2x4) e b (4x3) satisfazem essa condição. O resultado é uma nova matriz de dimensões 2x3, que é o número de linhas da primeira matriz e o número de colunas da segunda matriz.

Desde que a e b são bidimensionais, np.dot(a, b) e np.matmul(a, b) realizam a mesma operação de multiplicação de matrizes e, portanto, produzem o mesmo resultado.

> Multiplicação de Arrays Multidimensionais (N > 2)

In [50]:
# Dois arrays de 3 dimensões cada um
a = np.random.rand(2,3,3)
b = np.random.rand(2,3,3)

In [51]:
a.shape

(2, 3, 3)

In [52]:
b.shape

(2, 3, 3)

In [53]:
c = np.matmul(a, b)

In [54]:
d = np.dot(a, b)

In [55]:
print(c, c.shape)

[[[1.50389419 0.18794399 0.74554223]
  [1.51969686 0.17957493 0.53666115]
  [1.90474531 0.23361319 0.73847203]]

 [[0.15866109 0.70919519 0.19808669]
  [0.20983728 1.54369218 1.03962793]
  [0.12641806 0.66432001 0.28399011]]] (2, 3, 3)


In [56]:
print(d, d.shape)

[[[[1.50389419 0.18794399 0.74554223]
   [0.22163397 1.25284158 0.61237223]]

  [[1.51969686 0.17957493 0.53666115]
   [0.16484934 1.25650905 0.87197327]]

  [[1.90474531 0.23361319 0.73847203]
   [0.20622902 1.49887762 0.9966946 ]]]


 [[[0.7485504  0.09318426 0.4793761 ]
   [0.15866109 0.70919519 0.19808669]]

  [[1.62734402 0.17626701 0.52599264]
   [0.20983728 1.54369218 1.03962793]]

  [[0.95493118 0.13144543 0.53510238]
   [0.12641806 0.66432001 0.28399011]]]] (2, 3, 2, 3)


**Atenção:**

- A função matmul() usa o array como uma pilha de matrizes como elementos que residem nos dois últimos índices, respectivamente. 

- A função dot(), por outro lado, realiza a multiplicação como a soma dos produtos sobre o último eixo da primeira matriz e o penúltimo da segunda.

- Outra diferença entre matmul() e a função numpy.dot é que a função matmul() não pode realizar multiplicação de array com valores escalares.

Resumindo, o produto escalar é a soma dos produtos de valores em dois vetores de mesmo tamanho e a multiplicação de matrizes é uma versão matricial do produto escalar com duas matrizes.

### Norma da Matriz

> Isso é o produto escalar com apenas um valor (norma):

In [57]:
# Calculando a norma Frobenius, que é a raiz quadrada da soma dos quadrados de todos os elementos
produto_escalar_matriz = np.sqrt(np.sum(a ** 2))
print(produto_escalar_matriz)

2.8319845789792817


A norma Frobenius de uma matriz é definida como a raiz quadrada da soma dos quadrados de todos os seus elementos. Essencialmente, é como se você "achatasse" a matriz em um longo vetor e calculasse seu produto escalar.

In [58]:
%reload_ext watermark
%watermark -a "Data Science Academy"

Author: Data Science Academy



In [59]:
#%watermark -v -m

In [60]:
#%watermark --iversions

## Fim